In [1]:
from random import random
from funcoes import sigmoid
import numpy as np

In [2]:
"""
CONFIGURAÇÕES: 

quantidade de camadas,
quantidade de neurônios em cada camada,
função de ativação
"""

dimensoes_camadas = [2,2,1]


In [3]:
dados = [
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]

y = [
    0,
    1,
    1,
    0
]

In [10]:
def gerar_um_peso():
    """Sorteia um número entre -1 e 1"""
    sinal, numero = random(), random()
    
    if sinal >= 0.5:
        return numero
    else:
        return -numero
    
def gerar_N_pesos(n):
    """Gera um array de números sorteados"""
    return np.array([gerar_um_peso() for i in range(n)])

def gerar_rede(dimensoes):
    """
    Recebe a quantidade de neurônios em cada camada
    Gera pesos aleatoriamente.
    
    Observação: camadas de neurônios é uma coisa, camada de pesos é outra
    se eu tiver duas camadas de neurônios, eu tenho uma camada de pesos, que 
    liga essas duas camadas de neurônios
    
    O retorno é no formato
    
    [ <-- no primeiro nível, temos uma lista de camadas de pesos
    
        [ <-- para cada camada, temos uma lista de neurônios
        
            [ <-- para cada neurônio, temos uma lista de pesos
            
                0.2, 0.1, ...
            ]
        ]
    ]
    
    exemplo: gerar_rede([1,1]) gera pesos para uma rede com duas camadas de neurônios,
    com um neurônio em cada camada. Se temos duas camadas de neurônios, vamos ter uma camada
    de pesos.
    
    Resultado:
    rede = gerar_rede([1,1])  # [[[0.5]]], que é uma lista de camadas
    print(rede[0])            # [[0.5]]  , que é a lista de neurônios para a primeira camada
    print(rede[0][0])         # [0.5]    , que é a lista de pesos para o primeiro neurônio na primeira camada
    print(rede[0][0][0])      # 0.5      , que é o primeiro peso do primeiro neurônio da primeira camada
    """
    rede = []
    
    for dim in range(1, len(dimensoes)):
        rede.append(np.array([gerar_N_pesos(dimensoes[dim-1]) for i in range(dimensoes[dim])]))
        
    return np.array(rede)

def printar_rede(rede):
    """Printa as camadas de pesos da rede"""
    
    for i,camada in enumerate(rede):
        print("Camada %d:" % i)
        for j,neuronio in enumerate(camada):
            print("\tNeurônio %d:" % j)
            for w, peso in enumerate(neuronio):
                print("\t\tPeso %d:  %.3f" % (w, peso))
                
def forward(rede, entrada):
    """
    Pega a entrada, e faz todos os cálculos pra obter a saída
    Ou seja, faz as multiplicações pelos pesos, joga nas funções
    de ativação, e passa em todas camadas, pra retornar o que sobra
    na camada de saída
    """
    
    dados = entrada
    
    for camada in rede:
        # Aplica a soma ponderada pelos pesos
        dados = np.sum(dados * camada, axis=1)
        
        # Aplica a função de ativação
        dados = sigmoid(dados)
    
    return dados
    

In [30]:
rede = gerar_rede([2,2])
printar_rede(rede)

Camada 0:
	Neurônio 0:
		Peso 0:  0.188
		Peso 1:  0.353
	Neurônio 1:
		Peso 0:  -0.977
		Peso 1:  0.815


In [31]:
a = np.array([1,2])
rede[0]

array([[ 0.18793341,  0.35287888],
       [-0.97685521,  0.81468368]])

In [32]:
np.sum(a*rede[0], axis=1)

array([0.89369118, 0.65251216])

In [34]:
forward(rede, a)

array([0.70965131, 0.65757635])

In [15]:
sigmoid(0.4884)

0.619729440865097

In [26]:
sigmoid(-0.858 - 2 * 0.894)

0.0662359757466775

In [33]:
a

array([1, 2])